name = "lunatv-cf"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "lunatv"
database_id = "7e011ef1-e7fe-428f-81dc-630c3441904a"

[[kv_namespaces]]
binding = "KV"
id = "aea7dbd0f3a24b01a5f9de00f91ff4d7"
